// Generated by tools/manifest/generate.ts. Do not edit.
export const bundledViemArtifactDigests = Object.freeze({
  'viem-public.v1.json': 'sha256:f8e99a61058bd82cb873eab55dca343046c5e31e2e08a5454385033722a66a41',
  'viem-wallet.v1.json': 'sha256:6a5d76b056bded901b66019f4b97a75d478a0f68e84f61d2101824452a15937a',
  'viem-report.v1.json': 'sha256:cce20deb905ab58343c9b73a7e66f1b83d457743af8516794588d27d10e2798b',
} as const)
