// Generated by tools/manifest/generate.ts. Do not edit.
export const bundledAgentSdkArtifactDigests = Object.freeze({
  'agent-sdk.v1.json': 'sha256:a5d756d16fc25f030da07a6cac2849942bd5be06bcfaa4cbda74c424350c6d6b',
  'agent-sdk-report.v1.json': 'sha256:48a8bec247c71f83e5080c14b6164d416ba1450535d596e60b1fa1a15e365b13',
} as const)
