// Generated by tools/manifest/generate.ts. Do not edit.
export const bundledChatArtifactDigests = Object.freeze({
  'telegram.v1.json': 'sha256:87f08538816a2bbbca37f69d8279b1e52a504e55d8881517e99e9515bde0052b',
  'telegram-report.v1.json': 'sha256:c4911b57810221315256686e7cadffff8999c26ba5b1644c0f86537b01f651ec',
  'discord.v1.json': 'sha256:c5393ac9df404112fd2d9f26b4e07678fefc09c28f3b90d5a0e0f5f0cc7acab0',
  'discord-report.v1.json': 'sha256:d7481ecaa5760d3fad6c16396ff1d879aae77eb2017333c3d4c66b37f7be993a',
} as const)
