export const expectedPublicChainTools = [
  'workflow.chain.public.create_access_list',
  'workflow.chain.public.estimate_contract_gas',
  'workflow.chain.public.estimate_fees_per_gas',
  'workflow.chain.public.estimate_gas',
  'workflow.chain.public.estimate_max_priority_fee_per_gas',
  'workflow.chain.public.get_balance',
  'workflow.chain.public.get_blob_base_fee',
  'workflow.chain.public.get_block_number',
  'workflow.chain.public.get_block_receipts',
  'workflow.chain.public.get_block_transaction_count',
  'workflow.chain.public.get_chain_id',
  'workflow.chain.public.get_ens_address',
  'workflow.chain.public.get_ens_avatar',
  'workflow.chain.public.get_ens_name',
  'workflow.chain.public.get_ens_resolver',
  'workflow.chain.public.get_ens_text',
  'workflow.chain.public.get_fee_history',
  'workflow.chain.public.get_gas_price',
  'workflow.chain.public.get_proof',
  'workflow.chain.public.get_raw_transaction',
  'workflow.chain.public.get_transaction',
  'workflow.chain.public.get_transaction_confirmations',
  'workflow.chain.public.get_transaction_count',
  'workflow.chain.public.get_transaction_receipt',
  'workflow.chain.public.read_contract',
  'workflow.chain.public.verify_hash',
  'workflow.chain.public.verify_message',
] as const

export const expectedWalletChainTools = [
  'workflow.chain.wallet.deploy_contract',
  'workflow.chain.wallet.send_transaction',
  'workflow.chain.wallet.send_transaction_sync',
  'workflow.chain.wallet.sign_message',
  'workflow.chain.wallet.sign_transaction',
  'workflow.chain.wallet.write_contract',
  'workflow.chain.wallet.write_contract_sync',
] as const

export const expectedWorkflowTools = [
  'workflow.anchor.erc8263.on_chain_proof.anchor',
  'workflow.anchor.erc8263.on_chain_proof.anchor_with_aux',
  'workflow.execution.erc8301.agent_workflow.get_reply',
  'workflow.execution.erc8301.agent_workflow.get_task',
  'workflow.execution.erc8301.agent_workflow.on_agent_prove',
  'workflow.execution.erc8301.agent_workflow.on_agent_reply',
  'workflow.execution.erc8301.agent_workflow.result',
  'workflow.execution.erc8301.agent_workflow.run',
  'workflow.execution.erc8301.recompute.compute_reply_hash',
  'workflow.execution.erc8301.recompute.compute_task_hash',
  'workflow.identity.erc8004.identity_registry.get_agent_uri',
  'workflow.identity.erc8004.identity_registry.get_agent_wallet',
  'workflow.identity.erc8004.identity_registry.get_metadata',
  'workflow.identity.erc8004.identity_registry.owner_of',
  'workflow.identity.erc8004.identity_registry.register',
  'workflow.identity.erc8004.identity_registry.set_agent_uri',
  'workflow.identity.erc8004.identity_registry.set_agent_wallet',
  'workflow.identity.erc8004.identity_registry.set_metadata',
  'workflow.identity.erc8004.identity_registry.unset_agent_wallet',
  'workflow.identity.erc8004.recompute.compute_agent_id',
  'workflow.identity.erc8323.source_binding.bound_collection',
  'workflow.identity.erc8323.source_binding.get_source_nft',
  'workflow.identity.erc8323.source_binding.has_source_nft',
  'workflow.identity.erc8323.source_binding.is_source_nft_ownership_valid',
  'workflow.identity.erc8323.source_binding.register',
  'workflow.identity.erc8323.source_binding.supports_source_binding',
  'workflow.reputation.erc8275.agent_reputation.get_decay_weight',
  'workflow.reputation.erc8275.agent_reputation.get_reputation',
  'workflow.reputation.erc8275.agent_reputation.verify_outcome',
  'workflow.reputation.erc8275.recompute.compute_win_rate',
  'workflow.settlement.erc8203.consult_escrow.get_job',
  'workflow.settlement.erc8203.consult_escrow.open',
  'workflow.settlement.erc8203.consult_escrow.parse_opened',
  'workflow.settlement.erc8203.consult_escrow.parse_refunded',
  'workflow.settlement.erc8203.consult_escrow.parse_released',
  'workflow.settlement.erc8203.consult_escrow.refund',
  'workflow.settlement.erc8203.consult_escrow.release',
  'workflow.settlement.erc8203.consult_escrow.verify',
  'workflow.settlement.erc8203.recompute.compute_verdict_hash',
  'workflow.verify.erc8274.agent_verifier.verify',
  'workflow.verify.erc8274.get_trusted_verifier',
  'workflow.verify.erc8274.proof_verifier.proof_profile',
  'workflow.verify.erc8274.proof_verifier.proof_system',
  'workflow.verify.erc8274.proof_verifier.verify',
  'workflow.verify.erc8281.observation_commitment.parse_recorded_event',
  'workflow.verify.erc8281.observation_commitment.record',
  'workflow.verify.erc8281.observation_commitment.supports_observation_commitment',
  'workflow.verify.erc8281.recompute.compute_observation_digest',
  'workflow.verify.erc8299.compute_raw_proposal_hash',
  'workflow.verify.erc8299.compute_verdict_hash',
  'workflow.verify.erc8299.judgment_execution.proof_system',
  'workflow.verify.erc8299.judgment_execution.verify',
  'workflow.verify.erc8299.recompute.compute_raw_input_hash',
  'workflow.verify.erc8299.recompute.compute_sanitization_pipeline_hash',
  'workflow.verify.erc8299.wyriwe_attestation.proof_system',
  'workflow.verify.erc8299.wyriwe_attestation.verify',
] as const

export const expectedSkillTools = [
  'collaboration.get',
  'role.get',
  'tas.get',
  'tawg.get',
] as const

export const expectedIdentityTools = [
  ...expectedSkillTools,
  ...expectedPublicChainTools,
  ...expectedWalletChainTools,
].toSorted()

export const expectedTawgTools = [
  'profile.get',
  'profile.get_agent',
  ...expectedIdentityTools,
].toSorted()

export const expectedTelegramChatTools = [
  'chat.telegram.api.approve_chat_join_request',
  'chat.telegram.api.approve_suggested_post',
  'chat.telegram.api.ban_chat_member',
  'chat.telegram.api.ban_chat_sender_chat',
  'chat.telegram.api.close_forum_topic',
  'chat.telegram.api.close_general_forum_topic',
  'chat.telegram.api.create_chat_invite_link',
  'chat.telegram.api.create_chat_subscription_invite_link',
  'chat.telegram.api.create_forum_topic',
  'chat.telegram.api.decline_chat_join_request',
  'chat.telegram.api.decline_suggested_post',
  'chat.telegram.api.delete_all_message_reactions_chat',
  'chat.telegram.api.delete_all_message_reactions_user',
  'chat.telegram.api.delete_chat_photo',
  'chat.telegram.api.delete_chat_sticker_set',
  'chat.telegram.api.delete_ephemeral_message',
  'chat.telegram.api.delete_forum_topic',
  'chat.telegram.api.delete_message',
  'chat.telegram.api.delete_message_reaction_chat',
  'chat.telegram.api.delete_message_reaction_user',
  'chat.telegram.api.delete_messages',
  'chat.telegram.api.edit_chat_invite_link',
  'chat.telegram.api.edit_chat_subscription_invite_link',
  'chat.telegram.api.edit_forum_topic',
  'chat.telegram.api.edit_general_forum_topic',
  'chat.telegram.api.export_chat_invite_link',
  'chat.telegram.api.get_chat_administrators',
  'chat.telegram.api.get_chat_gifts',
  'chat.telegram.api.get_chat_member',
  'chat.telegram.api.get_chat_member_count',
  'chat.telegram.api.get_game_high_scores',
  'chat.telegram.api.get_user_chat_boosts',
  'chat.telegram.api.hide_general_forum_topic',
  'chat.telegram.api.leave_chat',
  'chat.telegram.api.pin_chat_message',
  'chat.telegram.api.promote_chat_member',
  'chat.telegram.api.remove_chat_verification',
  'chat.telegram.api.reopen_forum_topic',
  'chat.telegram.api.reopen_general_forum_topic',
  'chat.telegram.api.restrict_chat_member',
  'chat.telegram.api.revoke_chat_invite_link',
  'chat.telegram.api.send_gift_to_channel',
  'chat.telegram.api.send_message_draft',
  'chat.telegram.api.set_chat_administrator_custom_title',
  'chat.telegram.api.set_chat_description',
  'chat.telegram.api.set_chat_member_tag',
  'chat.telegram.api.set_chat_permissions',
  'chat.telegram.api.set_chat_sticker_set',
  'chat.telegram.api.set_chat_title',
  'chat.telegram.api.unban_chat_member',
  'chat.telegram.api.unban_chat_sender_chat',
  'chat.telegram.api.unhide_general_forum_topic',
  'chat.telegram.api.unpin_all_chat_messages',
  'chat.telegram.api.unpin_all_forum_topic_messages',
  'chat.telegram.api.unpin_all_general_forum_topic_messages',
  'chat.telegram.api.unpin_chat_message',
  'chat.telegram.events.wait',
] as const

export const expectedDiscordChatTools = [
  'chat.discord.events.wait',
  'chat.discord.message_manager.delete',
  'chat.discord.message_manager.pin',
  'chat.discord.message_manager.react',
  'chat.discord.message_manager.unpin',
] as const

export const expectedMemberTools = [
  'proof_provider.attestation.list',
  'repo.get',
  'repo.issue.list',
  'repo.pull_request.list',
  'repo.commit.list',
  'workflow.source.get',
  'workflow.source.verify',
  'workflow.da.capabilities',
  'workflow.da.get',
  'workflow.da.put',
  ...expectedWorkflowTools,
  ...expectedTawgTools,
].toSorted()

export const expectedTelegramMemberTools = [
  ...expectedMemberTools,
  ...expectedTelegramChatTools,
].toSorted()

export const expectedDiscordMemberTools = [
  ...expectedMemberTools,
  ...expectedDiscordChatTools,
].toSorted()

export const expectedTelegramDiscordMemberTools = [
  ...expectedMemberTools,
  ...expectedTelegramChatTools,
  ...expectedDiscordChatTools,
].toSorted()
