export const tasErrorCodes = [
  'CONFIG_FILE_NOT_FOUND',
  'CONFIG_PARSE_FAILED',
  'CONFIG_VERSION_UNSUPPORTED',
  'CONFIG_FIELD_INVALID',
  'CONFIG_CONFLICT',
  'CONFIG_ENV_REQUIRED',
  'CONFIG_REFERENCE_INVALID',
  'CONFIG_CLIENT_UNSUPPORTED',
  'INSTANCE_ALREADY_RUNNING',
  'INSTANCE_LOCK_FAILED',
  'TAS_SKILL_BUNDLE_INVALID',
  'PROFILE_INCONSISTENT',
  'REPOSITORY_LOCATOR_UNSUPPORTED',
  'REPOSITORY_CURSOR_INVALID',
  'REPOSITORY_CURSOR_CONTEXT_MISMATCH',
  'REPOSITORY_NOT_FOUND',
  'REPOSITORY_FETCH_FAILED',
  'REPOSITORY_RATE_LIMITED',
  'DA_REFERENCE_INVALID',
  'DA_PATH_INVALID',
  'DA_UNAVAILABLE',
  'DA_FETCH_FAILED',
  'DA_WRITE_FAILED',
  'DA_CONTENT_TOO_LARGE',
  'SKILL_NOT_FOUND',
  'SKILL_INVALID',
  'SKILL_ROLE_INVALID',
  'SKILL_MEMBER_CONTEXT_REQUIRED',
  'SKILL_FETCH_FAILED',
  'SKILL_CONTENT_TOO_LARGE',
  'FINALITY_UNSUPPORTED',
  'HISTORICAL_STATE_UNAVAILABLE',
  'RESOLUTION_CONFLICT',
  'EXTERNAL_UNAVAILABLE',
  'INVALID_ARGUMENT',
  'CREDENTIAL_REQUIRED',
  'AUTHORIZATION_DENIED',
  'WALLET_MISMATCH',
  'MANIFEST_BINDING_UNSUPPORTED',
  'WORKFLOW_SOURCE_UNAVAILABLE',
  'WORKFLOW_METADATA_INVALID',
  'WORKFLOW_COMPILER_UNAVAILABLE',
  'WORKFLOW_COMPILER_BUSY',
  'WORKFLOW_COMPILE_FAILED',
  'WORKFLOW_DEPLOYMENT_UNSUPPORTED',
  'WORKFLOW_SOURCE_VERIFICATION_REQUIRED',
  'OPERATION_OUTCOME_UNKNOWN',
] as const

export type TasErrorCode = (typeof tasErrorCodes)[number]
export type TasErrorDetails = Readonly<Record<string, string>>

export class TasError extends Error {
  readonly code: TasErrorCode
  readonly details?: TasErrorDetails

  constructor(code: TasErrorCode, message: string, details?: TasErrorDetails) {
    super(message)
    this.name = 'TasError'
    this.code = code
    this.details = details
  }
}
